version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/go-rest-api internal/main.go
      - GOOS=windows GOARCH=amd64 go build -o bin/go-rest-api-win-64.exe internal/main.go
      - GOOS=windows GOARCH=386 go build -o bin/go-rest-api-win-386.exe internal/main.go
      - GOOS=linux GOARCH=amd64 go build -o bin/go-rest-api-linux-64 internal/main.go
      - GOOS=windows GOARCH=386 go build -o bin/go-rest-api-linux-386 internal/main.go
      - GOOS=darwin GOARCH=amd64 go build -o bin/go-rest-api-darwin-64 internal/main.go

  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run internal/main.go

  swagger.gen:
    desc: Generate Go code
    cmds:
      - GOFLAGS=-mod=mod go generate github.com/Jd4rc3/go-rest-api/internal github.com/Jd4rc3/go-rest-api/pkg/swagger

  swagger.validate:
    desc: Validate swagger
    cmds:
      - swagger validate pkg/swagger/swagger.yml

  swagger.doc:
    desc: Doc for swagger
    cmds:
      - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html